/**
 * Publication Overview — PDF Export + Styling plug-in for WoodWing Studio
 *
 * Adds to the Publication Overview (triple-dot menu, top right):
 *  - "Export PDF…": merge the per-page print PDFs Studio Server already stores
 *    ('output' renditions, falling back to JPG page previews) into a single
 *    downloadable PDF — entire issue, a page range, filtered by workflow
 *    status and/or edition.
 *  - Styling: "sent to press" badge on page tiles, a diagonal watermark over
 *    press-status thumbnails, status color accents, late (past hard deadline)
 *    and approaching (past soft deadline) highlights, and a density control.
 *    Pure CSS/DOM decoration, fully reversible, self-disables if the Studio DOM
 *    changes. (Watermark and deadline looks are editable CSS blocks in
 *    src/70-styling-engine.js.)
 *
 * Runs inside the Publication Overview child application (same-origin iframe)
 * where the PoUiSdk and the relayed ContentStationSdk globals are available.
 *
 * GENERATED FILE NOTICE: dist/pub-overview-plugin.js is generated by
 * build-plugin.js from the files in src/ — edit those and rebuild.
 *
 * Registration (WoodWing Cloud): Management Console → Integrations →
 * Plug-ins → Publication Overview → Add new → URL of the dist file.
 */
(function () {
  'use strict';

  var VERSION = '0.3.0';
  var TAG = '[pub-pdf]';

  if (typeof PoUiSdk === 'undefined') {
    // Not in a Publication Overview context (or loaded in the wrong plugin
    // slot in the Management Console) — do nothing, never break the page.
    console.warn(TAG + ' PoUiSdk not available — plug-in not loaded in a Publication Overview context.');
    return;
  }
